version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '../nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '../../client/build:/etc/nginx/http'
    ports:
      - ${PORT}:80
    restart: 'unless-stopped'
  app:
    build:
      context: ../../server
    container_name: app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - ../../server:/server # host <-> container의 server 디렉토리를 공유
      - /server/node_modules
    restart: 'unless-stopped'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - '../mysql/init/:/docker-entrypoint-initdb.d/'
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    container_name: db
volumes:
  mysql_data:
