version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '../../nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '../../../client/build:/etc/nginx/http'
    ports:
      - ${PORT}:80
  app:
    build:
      context: ../../../server
    container_name: app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - ../../../server:/server # host <-> container의 server 디렉토리를 공유
      - /server/node_modules
    restart: 'unless-stopped'
